### ISSUE TITLE
Can i use this plugin in Vue?

### ISSUE THREAD

**Issue by Yhspehy** [ashhitch/vs-code-css-comments#11]
```js
<template></template>
<script></script>
<style scoped>
    use it here.....
</style>
```

I really want to use this plugin when i use Vue.

**Comment by ashhitch** [comment]
@Yhspehy will have a look into this for you Vue uses a .vue extension for its files right?

**Comment by Yhspehy** [comment]
@ashhitch yeah！

**Comment by nereuseng** [comment]
+1 for this. It will great to support .vue file

**Comment by ashhitch** [comment]
Thanks for the feedback, will add this into the next release!

**Comment by ashhitch** [comment]
Sorry about the delay in getting this added the latest version should now work with vue files, let me know if you have any issues!
