### ISSUE TITLE
Explain any key commands

### ISSUE THREAD

**Issue by mehas** [ashhitch/vs-code-css-comments#2]
What is a tab trigger? What key commands do I use to use your plugin?

**Comment by ScriptPup** [comment]
I think this is a good question, I'm not sure how this is supposed to work. Hitting tab, typing something, then pressing enter doesn't work... If that's the intent?

**Comment by ScriptPup** [comment]
Ah.. For anyone else who comes here looking... It's very literal. Hit the tab key, then type comment or whatever other option is specified.
