### ISSUE TITLE
Allow expansion in all file types

### ISSUE THREAD

**Issue by iaremarkus** [ashhitch/vs-code-css-comments#3]
Used + loved this plugin from SublimeText 3. Have just moved to VSCode and I see it only works in CSS type files?

Any chance it could be updated to work in any file type? PHP/HTML etc?

**Comment by nealoke** [comment]
+1 @ashhitch, also coming from sublime text and I really liked it but as @wondergryphon mentioned, only works in css, should work in js / jsx / other languages as well :)

**Comment by ashhitch** [comment]
will look at adding this to the next release.

**Comment by nealoke** [comment]
@ashhitch that would be so nice :) any idea on when this will be? :p would love to move to vscode but this and a few other are blocking me ;) love the plugin!

**Comment by ashhitch** [comment]
I have now added support for CSS comments in JSX and HTML files

**Comment by nealoke** [comment]
@ashhitch Thanks!
